### PR TITLE
Use `ruff format` as our Python formatter

### PR DESCRIPTION
**Pull request by emilk**
### What
`ruff format` is much faster.

But, it is still in beta: https://github.com/astral-sh/ruff/milestone/6

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3839) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/3839)
- [Docs preview](https://rerun.io/preview/531ebc67d6e379441467e7c936564b7158aac8bb/docs) 
- [Examples preview](https://rerun.io/preview/531ebc67d6e379441467e7c936564b7158aac8bb/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

File: crates/re_types_builder/src/format/python.rs [hunk 1]
```diff
@@ -81,13 +84,13 @@ fn format_python_dir(dir: &Utf8PathBuf) -> anyhow::Result<()> {
...
+    // 1) Call ruff format, which among others things fixes line-length
+    // 2) Call ruff --fix, which requires line-lengths to be correct
+    // 3) Call ruff format again to cleanup some whitespace issues ruff might introduce
 
-    run_black_on_dir(dir).context("black")?;
-    run_ruff_on_dir(dir).context("ruff")?;
-    run_black_on_dir(dir).context("black")?;
+    run_ruff_format_on_dir(dir).context("ruff --format")?;
+    run_ruff_fix_on_dir(dir).context("ruff --fix")?;
+    run_ruff_format_on_dir(dir).context("ruff --format")?;
```
Comment (emilk) [inline crates/re_types_builder/src/format/python.rs:93]: I'm not sure this is needed

File: justfile [hunk 2]
```diff
@@ -97,15 +97,8 @@ py-build *ARGS:
...
-    # fix line-length (See: https://github.com/astral-sh/ruff/issues/1904).
-    #
-    # 1) Call black, which among others things fixes line-length
-    # 2) Call ruff, which requires line-lengths to be correct
-    # 3) Call black again to cleanup some whitespace issues ruff might introduce
-    black --config rerun_py/pyproject.toml {{py_folders}}
     ruff --fix --config rerun_py/pyproject.toml {{py_folders}}
-    black --config rerun_py/pyproject.toml {{py_folders}}
+    ruff format --config rerun_py/pyproject.toml {{py_folders}}
     blackdoc {{py_folders}}
```
Comment (emilk) [inline justfile:102]: this is now different from the codegen

File: rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py [hunk 3]
```diff
@@ -23,7 +23,9 @@ class Rotation3D(Rotation3DExt):
 
     # You can define your own __init__ function as a member of Rotation3DExt in rotation3d_ext.py
 
-    inner: datatypes.Quaternion | datatypes.RotationAxisAngle = field(converter=Rotation3DExt.inner__field_converter_override)  # type: ignore[misc]
+    inner: Union[datatypes.Quaternion, datatypes.RotationAxisAngle] = field(
+        converter=Rotation3DExt.inner__field_converter_override
+    )  # type: ignore[misc]
```
Comment (emilk) [inline rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py:28]: This diff makes `mypy` angry, for some reason:

```
❯ pixi run lint-py-mypy  rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py
rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py:27: error: Unsupported converter, only named functions, types and lambdas are currently supported  [misc]
```

File: crates/re_types_builder/src/format/python.rs [hunk 4]
```diff
@@ -78,16 +81,9 @@ fn format_path_for_tmp_dir(
...
-    // The order below is important and sadly we need to call black twice. Ruff does not yet
-    // fix line-length (See: https://github.com/astral-sh/ruff/issues/1904).
-    //
-    // 1) Call black, which among others things fixes line-length
-    // 2) Call ruff, which requires line-lengths to be correct
-    // 3) Call black again to cleanup some whitespace issues ruff might introduce
-
-    run_black_on_dir(dir).context("black")?;
-    run_ruff_on_dir(dir).context("ruff")?;
-    run_black_on_dir(dir).context("black")?;
```
Comment (emilk) [inline crates/re_types_builder/src/format/python.rs:90]: This was introduced in https://github.com/rerun-io/rerun/pull/2686

I'm not sure this is needed anymore, since the above PR didn't give a repro. Let's hope not?

File: pixi.toml [hunk 5]
```diff
@@ -36,9 +36,9 @@ lint-cpp-files = "clang-format --dry-run"
 lint-rerun = "python scripts/lint.py"
 lint-rs-files = "rustfmt --check"
 lint-rs-all = "cargo fmt --check"
-lint-py-black = "black --check --config rerun_py/pyproject.toml"
+lint-py-fmt-check = "ruff format --check --config rerun_py/pyproject.toml"
 lint-py-blackdoc = "blackdoc --check"
-lint-py-mypy = "mypy --install-types --non-interactive --no-warn-unused-ignore"
+lint-py-mypy = "mypy --no-warn-unused-ignore"
```
Comment (jleibs) [inline pixi.toml:41]: Any reason for this change? Without `--install-types --non-interactive` mypy complains about a bunch of things related to usage of `requests` in a fresh environment.

```
~/rerun$ rm -rf .pixi/
~/rerun$ pixi run lint-py-mypy
examples/python/signed_distance_fields/download_dataset.py:10: error: Library stubs not installed for "requests"  [import]
examples/python/raw_mesh/download_dataset.py:10: error: Library stubs not installed for "requests"  [import]
examples/python/objectron/download_dataset.py:9: error: Library stubs not installed for "requests"  [import]
examples/python/objectron/download_dataset.py:53: error: Returning Any from function declared to return "str"  [no-any-return]
examples/python/structure_from_motion/main.py:16: error: Library stubs not installed for "requests"  [import]
examples/python/rgbd/main.py:19: error: Library stubs not installed for "requests"  [import]
examples/python/dicom_mri/main.py:23: error: Library stubs not installed for "requests"  [import]
examples/python/segment_anything_model/main.py:30: error: Library stubs not installed for "requests"  [import]
examples/python/open_photogrammetry_format/main.py:21: error: Library stubs not installed for "requests"  [import]
examples/python/human_pose_tracking/main.py:17: error: Library stubs not installed for "requests"  [import]
examples/python/depth_guided_stable_diffusion/main.py:18: error: Library stubs not installed for "requests"  [import]
examples/python/controlnet/main.py:20: error: Library stubs not installed for "requests"  [import]
examples/python/controlnet/main.py:20: note: Hint: "python3 -m pip install types-requests"
examples/python/controlnet/main.py:20: note: (or run "mypy --install-types" to install all missing stub packages)
examples/python/controlnet/main.py:20: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
examples/python/face_tracking/main.py:17: error: Library stubs not installed for "requests"  [import]
examples/python/detect_and_track_objects/main.py:16: error: Library stubs not installed for "requests"  [import]
Found 14 errors in 13 files (checked 297 source files)
```

File: crates/re_types_builder/src/format/python.rs (hunk 4 above)
Comment (jleibs) [reply crates/re_types_builder/src/format/python.rs:90]: It was happening deterministically from codegen-generated code at the time.  We could check out the parent commit if we really want a repro.

As long as `ruff --format` is a no-op after running `cargo codegen` then I think we're good.

File: pixi.toml (hunk 5 above)
Comment (emilk) [reply pixi.toml:41]: I had mypy behaving weird and so I wanted to match what the CI was executing (`mypy --no-warn-unused-ignore` via `justfile py-lint`)

Comment (emilk) [reply pixi.toml:41]: Why doesn't the CI need `--install-types --non-interactive`? Would it be any downside adding it to the CI side?

File: crates/re_types_builder/src/format/python.rs (hunk 4 above)
Comment (emilk) [reply crates/re_types_builder/src/format/python.rs:90]: Great, then we are good!

File: justfile [hunk 6]
```diff
@@ -101,15 +101,9 @@ py-build *ARGS:
...
-    # fix line-length (See: https://github.com/astral-sh/ruff/issues/1904).
-    #
-    # 1) Call black, which among others things fixes line-length
-    # 2) Call ruff, which requires line-lengths to be correct
-    # 3) Call black again to cleanup some whitespace issues ruff might introduce
-    black --config rerun_py/pyproject.toml {{py_folders}}
+    # NOTE: the order here matches the one in `crates/re_types_builder/src/format/python.rs`:
     ruff --fix --config rerun_py/pyproject.toml {{py_folders}}
-    black --config rerun_py/pyproject.toml {{py_folders}}
+    ruff format --config rerun_py/pyproject.toml {{py_folders}}
```
Comment (Wumpf) [inline justfile:106]: is there a deeper story that this isn't a pixi task yet? There is a pixi task for checking but not for formatting 🤔

File: justfile [hunk 7]
```diff
@@ -101,15 +101,9 @@ py-build *ARGS:
...
     blackdoc {{py_folders}}
```
Comment (Wumpf) [inline justfile:107]: this seems to imply that there is still need for black? But it was removed from the pixi toml and everywhere else 🤔

**Review by Wumpf — APPROVED** [review]
lgtm! Left some questions about pixi ~ justfile discrepancies and `blackdoc`. I suppose that's still in flux

**Comment by jprochazk** [comment]
It should be fine to run just `ruff check --fix && ruff format` according to the author: https://x.com/charliermarsh/status/1717229721954799727?s=20

File: justfile (hunk 7 above)
Comment (emilk) [reply justfile:107]: `blackdoc` formats code in docstrings, which `ruff format` does not yet do: https://github.com/astral-sh/ruff/issues/7146

File: justfile (hunk 6 above)
Comment (emilk) [reply justfile:106]: I mean, this is the deeper story: https://github.com/rerun-io/rerun/issues/3717 :)

Comment (emilk) [reply justfile]: There is also the `{[py_folders}}` which I don't know if `pixi` supports. Anyway, this PR is not about moving more tasks into pixi

File: justfile (hunk 7 above)
Comment (emilk) [reply justfile]: I added a comment about this
