### ISSUE TITLE
`rr.init(spawn=True)` fails with conda-forge package due to rerun_bindings ImportError

### ISSUE THREAD

**Issue by terremat** [rerun-io/rerun#12946]
**Describe the bug**

In a fresh Pixi environment, installing `rerun-sdk` from conda-forge causes `rr.init(..., spawn=True)` to fail when spawning the Rerun Viewer:

```text
ImportError: cannot import name '_dec_active_tracing_sessions' from 'rerun_bindings.rerun_bindings'
```

Installing the same version of `rerun-sdk` from PyPI in an otherwise equivalent Pixi environment works correctly.

The Rerun CLI from the conda-forge environment also works when invoked directly (`rerun --version` and `rerun --connect ...`). The failure appears specifically when the Viewer is spawned by the Python SDK.

**To Reproduce**

1. Create a fresh Pixi project:

```bash
mkdir rerun-conda
cd rerun-conda
pixi init
pixi add "python=3.14"
pixi add rerun-sdk
pixi shell
```

This results in:

```toml
[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.14.*"
rerun-sdk = ">=0.38.1,<0.39"
```

2. Create `test.py`:

```python
import rerun as rr

rr.init("test", spawn=True)
```

3. Run:

```bash
python test.py
```

4. The spawned Viewer fails with the `rerun_bindings` ImportError shown below.

As a comparison, create an equivalent Pixi environment but install Rerun from PyPI:

```bash
mkdir rerun-pypi
cd rerun-pypi
pixi init
pixi add "python=3.14"
pixi add --pypi rerun-sdk
pixi shell
python test.py
```

The PyPI installation works correctly and the Viewer starts listening on port 9876.

**Expected behavior**

`rr.init("test", spawn=True)` should successfully spawn the Rerun Viewer when `rerun-sdk` is installed from conda-forge, as it does with the PyPI package.

**Screenshots**

N/A

**Backtrace**

```text
Traceback (most recent call last):
  File ".../.pixi/envs/default/bin/rerun", line 7, in <module>
    from rerun.__main__ import main
  File ".../.pixi/envs/default/lib/python3.14/site-packages/rerun_sdk/rerun/__init__.py", line 32, in <module>
    import rerun_bindings as bindings
  File ".../.pixi/envs/default/lib/python3.14/site-packages/rerun_bindings/__init__.py", line 6, in <module>
    from .rerun_bindings import (
    ...
    )
ImportError: cannot import name '_dec_active_tracing_sessions' from 'rerun_bindings.rerun_bindings'
(.../.pixi/envs/default/lib/python3.14/site-packages/rerun_bindings/rerun_bindings.abi3.so)

WARN re_sdk::spawn: Spawned Rerun Viewer did not bind to port 9876 in time.
ERROR re_sdk::recording_stream: Failed to flush previous sink: gRPC has been unable to connect
```

**Desktop (please complete the following [information](<gs://buildai-screened-usc/v1/clips/039e3f51-bad4-5cee-bde9-cb3714338cd0/assets/f580cb17-7ece-5bba-a602-8dce52428932.aac>)):**

* OS: Ubuntu 24.04.4 LTS (Noble), x86_64
* Kernel: Linux 7.0.0-31-generic
* Environment manager: Pixi
* Channel: conda-forge
* Python: 3.14.7

**Rerun version**

```text
rerun-cli 0.38.1
```

**Additional context**

The issue is reproducible in a completely fresh Pixi project containing only Python and `rerun-sdk`.

The following work correctly in the conda-forge environment:

```bash
rerun --version
rerun --connect rerun+http://127.0.0.1:9876/proxy
```

Spawning `rerun` manually from Python also works:

```bash
python -c 'import rerun, subprocess; subprocess.run(["rerun", "--version"])'
```

I also reproduced the same `_dec_active_tracing_sessions` error with `rerun-sdk 0.37.2` using both Python 3.13 and Python 3.14.

In contrast, `rerun-sdk 0.38.1` installed from PyPI with `pixi add --pypi rerun-sdk` works correctly with Python 3.14 and the same minimal script.

This seems to suggest an issue specific to the conda-forge package/build or its interaction with the Viewer spawning mechanism.

**Comment by ntjohnson1** [comment]
Thanks for filing this! Do you mind filing the same content to the feedstock? https://github.com/conda-forge/rerun-sdk-feedstock the conda build gets managed over there and since it looks conda specific looks like a build config that will need to get updated. (If you don't have a chance in a few days I'll just copy over and tag you)
